### ISSUE TITLE
Duplicate Proxy Calls

### ISSUE THREAD

**Issue by melloware** [Unleash/unleash-proxy-client-js#112]
### Describe the bug

Proxy is making 2 calls every time you can see my network log here.

![image](https://user-images.githubusercontent.com/4399574/191844055-2dc7c926-1be7-42b0-bc42-49dc6061c601.png)

### Steps to reproduce the bug

Just run React app with proxy and watch the F12 network traffic.

### Expected behavior

Only 1 call every 15 seconds

### Additional context

Config:
```js
const unleashInstance: IConfig = {
	url: process.env.REACT_APP_UNLEASH_SERVER!,
	clientKey: process.env.REACT_APP_UNLEASH_KEY!,
	refreshInterval: 15,
	appName: 'clm',
	environment: process.env.REACT_APP_UNLEASH_ENV!,
	disableMetrics: true
};
```

### Unleash version

Latest

### Subscription type

Open source

### Hosting type

Self-hosted

### SDK information (language and version)

"@unleash/proxy-client-react": "^3.3.0",

**Comment by sighphyre** [comment]
I suspect this only occurs on the React proxy side, I see the issue here: https://github.com/Unleash/proxy-client-react/issues/77

But we'll close this as a duplicate when we look into on the react proxy side if needed

**Comment by melloware** [comment]
Thank you for investigating!

**Comment by melloware** [comment]
Yep it does see: https://github.com/Unleash/proxy-client-react/pull/81 it has to do with React 18 Strict Mode causing two renders and triggering the client to start twice.
