### ISSUE TITLE
Right-hand side of instanceof is not an object

### ISSUE THREAD

**Issue by VaynePeng** [Unleash/unleash-proxy-client-js#123]
### Describe the bug

![image](https://user-images.githubusercontent.com/34956460/203124602-da76e0af-3161-43e0-994f-9dd2e23e8ad1.png)
An error is reported when the url is passed in a string
Maybe you need `Object.prototype.toString.call(url) === '[object URL]' ? url : new URL(url)`

**Comment by sighphyre** [comment]
Hey @VaynePeng, I'm not able to reproduce this and we have a few test cases that already cover passing in a string as a URL. Can you provide some details on what the error is  that you're seeing, what version of this library you're using and a minimal reproducible example? Thanks!
