### ISSUE TITLE
CDN client fails for feature toggle with conditional activation strategy

### ISSUE THREAD

**Issue by alushnikov** [Unleash/unleash-proxy-client-js#124]
### Describe the bug

CDN client fails when trying obtain feature flag value with conditional activation strategy.
Simple standard activation strategies do not have problems.

### Steps to reproduce the bug

1. Set up unleash docker + unleash proxy as per documentation
2. Create feature toggle with condition. In my case:
<img width="891" alt="image" src="https://user-images.githubusercontent.com/671636/204393366-3e8388bc-45af-477d-8f18-2fd0b90e415c.png">
3. Create a simple html page with

`<script src="https://unpkg.com/unleash-proxy-client@latest/build/main.min.js" type="text/javascript"></script>`

and js code:

```javascript
var config = {
      url: "http://localhost:3000/proxy",
      clientKey: "proxy-client-key",
      appName: "test"
  };
    
vat client = new unleash.UnleashClient(config);
client.updateContext({ hostName: "test.co" });
client.start();

function logFeatureFlag() {
    isTenantEnabled = client.isEnabled("per-tenant-feature");

    console.log({ isTenantEnabled: isTenantEnabled });
};

setInterval(logFeatureFlag, 5000);
```

### Expected behavior

Feature Flag value obtained successfully

### Logs, error output, etc.

```bash
main.min.js:1 Uncaught TypeError: q.randomFillSync is not a function
    at g (main.min.js:1:2075)
    at j (main.min.js:1:2508)
    at a.generateEventId (main.min.js:1:6730)
    at a.createBaseEvent (main.min.js:1:6944)
    at a.createImpressionEvent (main.min.js:1:6802)
    at f.isEnabled (main.min.js:1:9174)
    at logFeatureFlag (app.js? [sm]:328:1)
```

### Screenshots

<img width="440" alt="image" src="https://user-images.githubusercontent.com/671636/204393861-868148fd-1dfc-414d-8a14-72b335e7f16d.png">

### Unleash version

latest

### Subscription type

Open source

### Hosting type

Self-hosted

### SDK information (language and version)

latest, javascript

**Comment by Tymek** [comment]
Thank you for reporting and sorry for inconvenience 😔. I'll check what's going on. We probably need a polyfill like [crypto-browserify/randomfill](https://github.com/crypto-browserify/randomfill).

What browser are you using? Is it working fine with previous versions of the package?

**Comment by alushnikov** [comment]
I'm using Google Chrome Version 107.0.5304.110 (Official Build) (x86_64)

Actually that's the first time I've tried using unleash, so can not confirm if this worked with the previous versions.

**Comment by kwasniew** [comment]
@alushnikov can you try with the latest beta release:
 `<script src="https://unpkg.com/unleash-proxy-client@2.4.0-beta.1/build/main.min.js" type="text/javascript"></script>`
