### ISSUE TITLE
Add support to provide namePrefix and tags for filtering

### ISSUE THREAD

**Issue by omnichronous** [Unleash/unleash-proxy-client-js#165]
### Describe the feature request

Thank you for your work Unleash team. Is it possible to port the functionality from https://github.com/Unleash/unleash-client-node/pull/237 into this SDK too?

### Background

I have a codebase with multiple projects that sometimes share feature toggles and sometimes not. I'd like to be able to use tags in the Unleash Admin to designate which project uses which toggles and then in each project fetch only those toggles that are relevant to it.

**Comment by sighphyre** [comment]
Hey @omnichronous, this probably isn't on our radar right now. You're more than welcome to take a stab at a PR but we have other high priority changes that we're focusing on.

What problem is this actually causing for you? Are you trying to reduce network overhead here?

**Comment by omnichronous** [comment]
Thanks for your response @sighphyre. Yeah reducing network overhead is part of it, and another part is security - the same logic as returning only the currently enabled toggles when the client does a fetch.

What I'm really trying to do is integrate Unleash with my analytics solution. I want to create a "set it and forget it" mechanism to include the Unleash state in every event that's reported to my analytics tool. When that difference between 10 and 20 toggles gets multiplied by thousands and thousands of events it starts to have a real impact. That's why I'd like a way to filter out some of the toggles on the client side.

Even just getting the tags in the client would solve this for me, but I figured porting this functionality from the other SDK would be easier.

**Comment by Aaronius** [comment]
Related to this, is there a way to only request toggles for a specific project? It doesn't look like it.

**Comment by ivarconr** [comment]
> Related to this, is there a way to only request toggles for a specific project? It doesn't look like it.

Yes, as long as you use a project specific token together with the Unleash Frontend API or the Unleash Edge you will only get toggles for that project.

**Comment by ivarconr** [comment]
I am closing this as it is already supported by scoped API tokens.
