### ISSUE TITLE
Add esm bundle

### ISSUE THREAD

**Issue by badsgahhl** [Unleash/unleash-proxy-client-js#166]
### Describe the feature request

Currently the npm package doesn't provide an esm version of the bundle. For example the angular build process warns you about possible issues with the older formats.

### Solution suggestions

Add an esm version.

**Comment by badsgahhl** [comment]
Tried a fix in  #167 . Works in my angular project. Don't have any node project flying around to test it there.

**Comment by Tymek** [comment]
Hi! Sorry for a delayed response. It's a very valid request. You can expect a version with it published this week
