### ISSUE TITLE
feat:  Allow clients to only query feature toggles for given project Names. 

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash-proxy-client-js#17]

**Comment by ivarconr** [comment]
You can now scope the unleash-proxy  to only serve specific projects. Might be good to not have the complexity on the SDK side?

**Comment by siimsaar** [comment]
This would mean that it's necessary to create proxy instances for every project which is costly on the infrastructure side. Simply passing the project as a query param from the SDK should be relative minor complexity to add.

**Comment by ivarconr** [comment]
Good point. My concern was also that you might not want to expose all projects to the frontend.
