### ISSUE TITLE
Failed to parse source map Warning

### ISSUE THREAD

**Issue by sriadimanav** [Unleash/unleash-proxy-client-js#178]
### Describe the bug

package version: 3.1.0
react version: 18.2.0
react scripts version: 5.0.1

Getting warnings in console after upgrading to latest version

### Steps to reproduce the bug

install latest version using yarn

### Expected behavior

should not throw warnings

### Screenshots

<img width="1252" alt="image" src="https://github.com/Unleash/unleash-proxy-client-js/assets/30376679/3f65d08e-c143-425c-8694-c0415f0dd435">

### Unleash version

3.1.0

### Subscription type

None

### Hosting type

None

**Comment by sjaanus** [comment]
Hey @sriadimanav! 😊 To better assist you, could you let me know which npm version you're using?

**Comment by Tymek** [comment]
I was able to reproduce it with `create-react-app` Typescript template.
Related to cra discussion: https://github.com/facebook/create-react-app/discussions/11767

**Comment by Tymek** [comment]
Looks unrelated to Unleash. https://github.com/facebook/create-react-app/pull/11752

**Comment by Tymek** [comment]
After further investigation, maybe I'll be able to do something about this.

**Comment by Tymek** [comment]
Fixed in [`v3.1.1`](https://github.com/Unleash/unleash-proxy-client-js/releases/tag/v3.1.1)

**Comment by sriadimanav** [comment]
> Hey @sriadimanav! 😊 To better assist you, could you let me know which node version you're using? Also, did v3.0.0 work properly for you?
> 
> Currently was not able to reproduce by this. This gives the same versions you described.
> 
> ```
> npx create-react-app react-app
> cd react-app
> yarn install
> ```
> 
> Do you have anything else added that could cause this?

Node version: 20.8.0

**Comment by sriadimanav** [comment]
> Fixed in [`v3.1.1`](https://github.com/Unleash/unleash-proxy-client-js/releases/tag/v3.1.1)
> 
> CC @sriadimanav

thanks @Tymek
