### ISSUE TITLE
Silent errors for offline PWA

### ISSUE THREAD

**Issue by Tymek** [Unleash/unleash-proxy-client-js#188]
### Describe the feature request

I am trying to get rid of the console error Unleash: unable to fetch feature toggles TypeError: Failed to fetch when our PWA is offline. We are using the React Client, is there a way to remove the errors while offline?

### Background

https://unleash-community.slack.com/archives/C03GWTN7XMG/p1702460982222809

### Solution suggestions

I think we could introduce "silent" mode or log verbosity. Here is the line responsible for console errors, but `console.error` is in use also in other places: https://github.com/Unleash/unleash-proxy-client-js/blob/4a4056dd471ec58263ac11485feeb344e2c8578b/src/index.ts#L455

**Comment by mortengjesing** [comment]
A log verbosity would be nice 😄
