### ISSUE TITLE
Empty 'If-None-Match' header is send causing some firewalls to block the request

### ISSUE THREAD

**Issue by sebkasanzew** [Unleash/unleash-proxy-client-js#189]
### Describe the bug

Requests are made with headers always containing the `If-None-Match` header, even if there is no value.

if no `etag` is set, it defaults to `''` and thus the `If-None-Match` header is set with an empty value.

Some firewalls, like "F5" are blocking requests with empty headers by default.

### Steps to reproduce the bug

Don't set an etag

### Subscription type

None

### Hosting type

None

**Comment by Tymek** [comment]
Please try [v3.3](https://github.com/Unleash/unleash-proxy-client-js/releases/tag/v3.3.0)
