### ISSUE TITLE
Missing `currentTime` in Unleash Context object

### ISSUE THREAD

**Issue by AdrienFromToulouse** [Unleash/unleash-proxy-client-js#194]
### Describe the bug

The `currentTime` property https://docs.getunleash.io/reference/unleash-context seems to be missing.

https://github.com/Unleash/unleash-proxy-client-js/blob/main/src/index.ts#L9

Cheers!

### Steps to reproduce the bug

Try to set the `currentTime` property on the context, it would result in noop.

### Expected behavior

Take the `currentTime` property into account

### Unleash version

3.2.0

### Subscription type

Pro

### Hosting type

Hosted by Unleash

### SDK information (language and version)

"@unleash/proxy-client-react": "^4.1.1"

**Comment by sjaanus** [comment]
This is released as part of https://github.com/Unleash/unleash-proxy-client-js/releases/tag/v3.3.1

**Comment by AdrienFromToulouse** [comment]
Thanks!

**Comment by AdrienFromToulouse** [comment]
@sjaanus will it be incorporated to https://github.com/Unleash/proxy-client-react anytime soon?

Cheers,
