### ISSUE TITLE
Unleash-proxy-client-js: Conditionally add content-type only on post requests

### ISSUE THREAD

**Issue by Mostafa-Abdollahi** [Unleash/unleash-proxy-client-js#197]
### Describe the bug

the getHeaders function adds 'Content-Type': 'application/json' to GET method that is not a standard header, this header should be available in POST methods, you can fix this with an if condition.

### Subscription type

None

### Hosting type

None

**Comment by thomasheartman** [comment]
Hey, @Mostafa-Abdollahi ! Good point. You sure don't need the content-type header if you have no body. Thanks for reporting it. As you've probably seen, there's already a PR addressing this, so we'll get this handled shortly 😄
