### ISSUE TITLE
Service worker compatibility

### ISSUE THREAD

**Issue by jeremiewtd** [Unleash/unleash-proxy-client-js#201]
### Describe the feature request

We would like to use `unleash-proxy-client-js` in a service worker context, more precisely in the context of a browser extension service worker (and "non persistent background").

### Background

We are facing some issues while running `unleash-proxy-client-js` in a service worker context (browser extension service worker).

First issue : each time the proxy is instantiated, it fetches the flags, no matter how old they are in the storage. In the context of a service worker which stops and restarts multiple times depending on its use this will cause a huge overhead on our proxy server (we have hundreds of thousands of live extensions).

Second issue : the internal use of `setTimeout` and `setInterval` which is not compatible with the lifecycle of this kind of service workers which have to use "browser alarms" instead, see [documentation](https://developer.chrome.com/docs/extensions/develop/migrate/to-service-workers#convert-timers).

### Solution suggestions

For the first issue (fetch call on load) the solution could be to check "flag expiration" on load, if flags are younger than the "refreshInterval", it should not fetch (we have to store a new "last update" timestamp) OR use the `bootstrap` value on first load and don't fetch (wait for next refresh).

For the second issue (usage of `setInterval`), we could expose as public methods the "refresh" toggles and metrics so that library consumers can call them themself if needed (we could so add our own "alarm" to refresh the toggles and metrics).

**Comment by Tymek** [comment]
Part 1 in beta. [v3.6.0-beta.0](https://github.com/Unleash/unleash-proxy-client-js/releases/tag/v3.6.0-beta.0)

For "use of setTimeout and setInterval" part, we are open to contributions.

**Comment by jeremiewtd** [comment]
Thank you !

For "use of setTimeout and setInterval" part, we would like to make the `updateToggles` method public so that it could be called whenever needed, for our case using a "browser alarm" instead of `setInterval`.

We are preparing a pull request for this.

**Comment by ivarconr** [comment]
I think you suggestion makea sense. 

For my understanding, what you are purposing is to never "start" the unleash client (or set the intervals to 0) and instead take care of the poll schedule with a custom implementation?

**Comment by jeremiewtd** [comment]
Yes exactly
