### ISSUE TITLE
UserId strategy not working when compiled with XCode15 (IOS 17)

### ISSUE THREAD

**Issue by wahmedswl** [Unleash/unleash-proxy-client-js#204]
### Describe the bug

Hi!

UserId strategy is not working when React Native app is compiled with XCode 15. There seems to be multiple online threads that highlight this issue e.g https://forums.developer.apple.com/forums/thread/738432 and https://github.com/axios/axios/issues/6102. It was working fine untill XCode14 and it got broken after we migrated to XCode 15.

### Unleash version

Unleash 4.17.1 (Open Source)

### Subscription type

Open source

### Hosting type

Self-hosted

### SDK information (language and version)

unleash-proxy-client

**Comment by wahmedswl** [comment]
This issue seems be due to the way url encoding works and i guess moving to `usePOSTrequests` should resolve it. We are going to try this and will get back with the results.

**Comment by ivarconr** [comment]
It feels a bit out of our control if iOS17 breaks encoding, the SDK depends on browser specific APIs to URL encode the requests. 

I suspect you have an "@" in the userId? 

An alternative workaround would be to use some stort of custom encoding (always replace @ with "_" or something).

**Comment by wahmedswl** [comment]
@ivarconr Yes, we have @. `usePOSTrequests` this will not work?

**Comment by ivarconr** [comment]
usePOSTrequests will work if you connect to unleash-edge or unleash-proxy.

**Comment by wahmedswl** [comment]
@ivarconr Thanks! We have switched to `usePOSTrequests` and we are good now.
