### ISSUE TITLE
error "crypto.getRandomValues) not supported" in react-native application when using useVariant() in iOS simulator

### ISSUE THREAD

**Issue by Erwan-DATIN** [Unleash/unleash-proxy-client-js#223]
### error "crypto.getRandomValues) not supported" in react-native application (0.71) in iOS simulator

Currently testing unleash and more precisely **variants** I encounter an error (_does not occur in my testing web application_): 

> crypto.getRandomValues) not supported

### Steps to reproduce the bug

In a react-native application **(my rn version is currently v0.71.x**) `useVariant()`

```javascript
import { useVariant } from '@unleash/proxy-client-react';
///....
const myVariant = useVariant('myVariant'); // will lead to this error in iOS simulator
```

### Expected behavior

Should not throw this error

### Logs, error output, etc.

See screenshot below.

### Screenshots

![image](https://github.com/user-attachments/assets/b422cd5b-abb9-4b86-918b-8a2c3290a344) 

### Additional context

react-native 0.71+

### Unleash version

@unleash/proxy-client-react@4.3.0

### Subscription type

None

### Hosting type

Hosted by Unleash

**Comment by ivarconr** [comment]
Easiest way to fix this for end-users would be to install and add import 'react-native-get-random-values' at the top of their React Native / Expo app, like mentioned here: https://www.npmjs.com/package/uuid#react-native--expo

(already discussed in https://github.com/Unleash/unleash-proxy-client-js/issues/87)
