### ISSUE TITLE
POST method fails when using with new Unleash Edge service

### ISSUE THREAD

**Issue by mhuffsti** [Unleash/unleash-proxy-client-js#228]
I'm not sure if the issue is on the Edge side or within this unleash-proxy-client or maybe I should be using a completely different frontend JS client when switching from Proxy to Edge, but I'll start with this issue here.

I have the unleash-proxy-client setup and working fine and it is making its requests against an Unleash Edge server.  Everything seems to be working fine.  However, we wanted to switch from using GET to POST.  When we set usePOSTrequests to true, this part of the code:

https://github.com/Unleash/unleash-proxy-client-js/blob/81903aa93a2ca0ffc248064852e9d960e196a344/src/index.ts#L563

builds a POST payload that takes the form of (eg, a generalized example for illustration purposes):

**{"context":**{"sessionId":#######,"appName":"APP_NAME_HERE","environment":"ENV_NAME_HERE"}**}**

However, when that request hits the Edge server, it responds with:
`Json deserialize error: invalid type: map, expected a string at line 1 column ##
`

I did some testing, and if we remove the "context" piece and only send as the payload the contents of context, then the Edge server responds appropriately.

Question:

- Should I be using a different client against Edge?
- If not, then does this part of the code need to be updated to no longer inject {"context":... to the POST payload?

**Comment by chriswk** [comment]
Hi @mhuffsti , sorry for the delayed response. I've made https://github.com/Unleash/unleash-edge/pull/510 which should fix it, and will be released as soon as @sighphyre and myself can agree on the way forward.

**Comment by chriswk** [comment]
Way forward agreed. We'll release 19.3.1 sometime today and I'll update this again when you can upgrade your Edge.

**Comment by chriswk** [comment]
Hi @mhuffsti , could you please try to use 19.3.1. It worked for us, but not closing this ticket until I have confirmation from you that it works from your end.

**Comment by mhuffsti** [comment]
Thanks for looking into this so quickly.  I can confirm that it is better, yes, but maybe something more is needed in terms of the validation of the JSON POST payload on the Edge side?

Specifically, if I set usePOSTrequests to true on the proxy client, the 19.3.1 release of Edge is parsing the "context" part now.
If I set a sessionId as a string, then it seems quite happy.
However, if I let the proxy client autogenerate a sessionId, it generates a number and sends that number like this:

<img width="562" alt="image" src="https://github.com/user-attachments/assets/bac59388-a1c3-442d-86a6-6b8420ae68c7">

Edge then generates a 400 Bad request with this response:
Json deserialize error: invalid type: integer `299923022`, expected a string at line 1 column 33

Should it be expecting a string?  Or should it accept either a string or an integer?

**Comment by chriswk** [comment]
It should be expecting a string, at least that's what our schema says, but I guess proxy has just been tolerating this since it's javascript. But with actual typed languages, this breaks. I'll make a PR on this repo

**Comment by chriswk** [comment]
Ok, bugfix commited, will release a 3.6.1 of the client.

**Comment by chriswk** [comment]
3.6.1 released which will post sessionId as a string also if auto generated. Thanks for letting us know. Closing this issue now.
