### ISSUE TITLE
Gitlab - Feature Flags - 401 Unauthorized

### ISSUE THREAD

**Issue by jat10** [Unleash/unleash-proxy-client-js#24]
I am using [Feature Flags](https://docs.gitlab.com/ee/operations/feature_flags.html) in Gitlab so in the documentation they mention to used unleash. 

I went to **Deployment > Feature Flags** and created a flag called: `live-chat-settings`. Where also i got the URL that i will use in your library:
- URL: `https://gl.eweev.com/api/v4/feature_flags/unleash/***`
- clientKey (in gitlab it's called instanceId): `Ljf3c6-**********MhR`
- appName: `chat`

Under the **Deployment > Environments** I got the app name I have two:
- vuejs
- chat

I downloaded:
```npm
 npm install unleash-proxy-client --save
```

Where in the code i added the following:
```js
initUnleash() {
      const unleash = new UnleashClient({
        url: 'https://gl.eweev.com/api/v4/feature_flags/unleash/***',
        clientKey: 'Ljf3c6-**********MhR',
        appName: 'chat'
      })
      console.log('unleash: ', unleash)

      // Start the background polling
      unleash.start()
    },
```

Here is the console.log for the variable:
```js
{
    "toggles": [],
    "etag": "",
    "url": "https://gl.eweev.com/api/v4/feature_flags/unleash/***",
    "clientKey": "Ljf3c6-**********MhR",
    "storage": {
        "prefix": "unleash:repository"
    },
    "refreshInterval": 30000,
    "context": {
        "appName": "chat",
        "environment": "default"
    },
    "metrics": {
        "disabled": false,
        "metricsInterval": 30000,
        "appName": "chat",
        "url": "https://gl.eweev.com/api/v4/feature_flags/unleash/***",
        "started": "2021-07-29T13:39:10.438Z",
        "clientKey": "Ljf3c6-**********MhR",
        "bucket": {
            "start": "2021-07-29T13:49:01.292Z",
            "stop": null,
            "toggles": {}
        },
        "timer": 74
    },
    "e": {},
    "timerRef": 21
}

```

I am getting the following console error on my browser:
```
GET https://gl.eweev.com/api/v4/feature_flags/unleash/***?appName=chat&environment=default 401
```
Where the response to the API call is the following:
```js
{
    "message": "401 Unauthorized"
}
```

Anyone can help me?

**Comment by ivarconr** [comment]
This SDK is meant to connect via the Unleash Proxy. https://github.com/Unleash/unleash-proxy

I belive you will need the following PR to be merged before the proxy is gitlab compliant:
https://github.com/Unleash/unleash-proxy/pull/13

**Comment by jat10** [comment]
@ivarconr now what should we do for this issue to get fixed?

**Comment by ivarconr** [comment]
@jat10 you will need to set up the unleash-proxy and connect via that one.

**Comment by sebammon** [comment]
@jat10 Did you get this to work?

**Comment by sebammon** [comment]
For anyone else wondering the same, the answer is in the GitLab docs: https://docs.gitlab.com/ee/operations/feature_flags.html#unleash-proxy-example
