### ISSUE TITLE
How do I use my custom strategy?

### ISSUE THREAD

**Issue by PEZ** [Unleash/unleash-proxy-client-js#31]
Hello,

I spent a good part of yesterday pulling my hair because my test app wouldn't get flags enabled for my custom strategy (`fy-workspace` in the demo sandbox). Then I saw somewhere that for custom strategies the flags would always be `false` unless the client registers what custom strategies it wants to use. Since I don't quite know what I am doing I tried a lot of silly things. Here's two:

* I tried to just provide a `fy-workspace` as a string to the `strategies` entry when creating the client. (I thought wth, worth a try 🤷 ).
* I  tried to import `Strategy` from the `unleash-proxy-client` and subclass it and such. (I didn't quite realize I was using the service via a proxy, because reasons)

Anyway, finally I realized I was using a proxy and that I need to run my own proxy in order to test my custom strategy. That's where I am now and I fail to get the proxy to start using my custom strategy. I am using the docker image and starting it like so:

```sh
docker run \
   -e UNLEASH_PROXY_SECRETS=some-secret \
   -e UNLEASH_URL=https://app.unleash-hosted.com/demo/api/ \
   -e UNLEASH_API_TOKEN=56907a2fa53c1d16101d509a10b78e36190b0f918d9f122d \
   -e UNLEASH_CUSTOM_STRATEGIES_FILE=/config/toggle-strategies.js \
   --mount type=bind,source="$(pwd)"/config,target=/config \
   -p 3333:3000 \
   unleashorg/unleash-proxy
```

And in my local directory in `./config/toggle-strategies.js` I have:

```javascript
const unleash = require('unleash-client');

class WorkspaceStrategy extends unleash.Strategy {
  constructor() {
    super('fy-workspace');
  }

  isEnabled(parameters, context) {
    return parameters['fy-workspace-id'].includes(context['fy-workspace-id']);
  }
}

module.exports = [new WorkspaceStrategy()];
```

I then get:

```
internal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'unleash-client'
Require stack:
- /config/toggle-strategies.js
- /unleash-proxy/dist/config.js
```

Side note: I first tried with ES6 syntax.

I think I am doing a lot of things wrong here, but I am out of wits.

Sorry if I am posting this in the wrong repo, it wasn't clear cut to me where it would go best. 😄

**Comment by ivarconr** [comment]
moving disussions to https://github.com/Unleash/unleash-proxy/issues/29

**Comment by PEZ** [comment]
Thanks!
