### ISSUE TITLE
Uncaught error bubbles up to the app

### ISSUE THREAD

**Issue by Sparragus** [Unleash/unleash-proxy-client-js#52]
If the proxy is unreachable when it's offline or blocked by the client, for example, this `fetch` will throw a runtime error that reaches the app.

https://github.com/Unleash/unleash-proxy-client-js/blob/c040f14d48f4740fd459c2d4c0fe7956da35f678/src/metrics.ts#L72-L81

I suggest we implement a try/catch just like it's being done in `index.ts`. https://github.com/Unleash/unleash-proxy-client-js/blob/d1d4ad29a12a6c652477525de2f27427dd40f72b/src/index.ts#L253-L288

As a side-note, on Next.js apps, this is very bothersome during development because it shows a modal displaying uncaught runtime errors. 
![image](https://user-images.githubusercontent.com/80982/144467484-4c011e59-4dc9-4cb7-999f-10292dfb47f2.png)

**Comment by ivarconr** [comment]
Makes sense @Sparragus 👍🏼 

I often forget that fetch uses a mix of throw and unsuccessful response codes, which often feels a bit clunky to get right. 

Generally the SDK should try to throw in any operation that happens in the background.

**Comment by raymzag** [comment]
Following as well. We are seeing these errors in our error loggings too.

**Comment by olav** [comment]
Should be fixed in the following versions:

```
unleash-proxy-client-js v2.1.0
@unleash/proxy-client-vue v0.0.4
@unleash/proxy-client-svelte v0.0.4
@unleash/proxy-client-react v3.3.0
```
