### ISSUE TITLE
When does the "update" event actually get triggered

### ISSUE THREAD

**Issue by snowfrogdev** [Unleash/unleash-proxy-client-js#62]
I've been experimenting with the library and I'm not quite clear on when the "update" event actually get triggered. I have registered a listener for the "update" event but it doesn't seem to get triggered.

I was expecting it to get triggered on the next poll, whenever one (or more) of the toggles was changed since the last poll, is that how it should work? To tests it I was simply turning a toggle on and off but the event is not getting triggered.

**Comment by ivarconr** [comment]
The update will trigger if the SDK gets 304 back from the proxy. This happens if the list of enabled feature toggles changes for the provided context.

**Comment by snowfrogdev** [comment]
🤔So an update should get triggered on each of those calls?
![image](https://user-images.githubusercontent.com/22530235/149849514-21b4454b-732f-4a67-8765-05f0024a53ac.png)
I'm confused, I thought a 304 status code normally meant nothing had changed and you could just use the cached data? See https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304

**Comment by snowfrogdev** [comment]
Ok, I can confirm that it works as intended, when the call returns a 200 OK, signifying that new information is available. The reason it wasn't working for me at first has nothing to do with the library and everything to do with the fact that I'm an idiot. I'm using the fromEvent() function from RxJS but I forgot to subscribe to the Observable. 🤦‍♂️Thanks for endulging me.

**Comment by ivarconr** [comment]
> everything to do with the fact that I'm an idiot

I doubt that is correct. I can relate to the feeling though. 

Thanks for confirming and closing the issue!
