### ISSUE TITLE
Remove react native dependency

### ISSUE THREAD

**Issue by jdussouillez** [Unleash/unleash-proxy-client-js#71]
The [@react-native-async-storage/async-storage](https://react-native-async-storage.github.io/async-storage/) is big, and it's only used in the file https://github.com/Unleash/unleash-proxy-client-js/blob/v1.11.0/src/storage-provider-local.ts.

When installing the unleash proxy client in my package.json, it installs 695 packages and add 180MB to my node_modules folder, mainly because of the react dependencies. It seems to be way too big to only get and set values in the localStorage. Moreover, we don't even use it and use a custom storage implementation.

Would it be possible to remove the react native dependency and use another lighter library when using the localStorage ? Or maybe creating another package to provide the default storage implementations (unleash-proxy-client-js-local-store, etc) ?

**Comment by thomasheartman** [comment]
Hey, @jdussouillez 👋🏼 

Thanks for opening the issue! I think you're right in that we can remove it. In fact, as discussed in [this PR on the React Proxy client](https://github.com/Unleash/proxy-client-react/pull/20), the inclusion here seemingly doesn't make it work for React Native users anyway. That said, I may well be missing something, so I'd like some input from @ivarconr too.
