### ISSUE TITLE
ready is fired even if unleash proxy is not ready?

### ISSUE THREAD

**Issue by janknobloch** [Unleash/unleash-proxy-client-js#90]
### Describe the bug

Hey there,

it seems that the ready event is triggered on the proxy client even if we disable our unleash proxy (or enter a wrong url for that matter):

``` 
this.unleash = new UnleashClient(config);

    // delegate checking feature toggles to unleash if available
    this.unleash.on('ready', () => {
      console.log('FeatureConfigService: Unleash is ready...');
      this.unleashReady = true;
    });
    this.unleash.on('update', () => {
      console.log('FeatureConfigService: Updating feature toggles...');
      this.unleashReady = true;
    });
    this.unleash.on('error', () => {
      console.log('FeatureConfigService: Could not reach unleash proxy, using defaults as fallback...');
      this.unleashReady = false;
    });
    this.unleash.start();
```

we get an error event and afterwards and ready event which basically breaks our boolean logic for our fallback.
We are using the ` "unleash-proxy-client": "^2.0.1",`

Please let me know if you need any further information.

### Expected behavior

Only be ready when you are really ready and do not fire a ready event in the case of an error, in particular after the error event.

**Comment by FredrikOseberg** [comment]
Interesting. Do you have any steps to reproduce this error? We'll want to look into this.

**Comment by sighphyre** [comment]
Some more info here - the proxy client listens to the ready event from the Node SDK to determine whether or not its ready. That event gets fired when the client is ready to receive isEnabled calls but potentially before the synchronized event is fired. Synchronized is fired once toggles have actually synced. We should definitely look into this

**Comment by olav** [comment]
Should be fixed by https://github.com/Unleash/unleash-proxy-client-js/pull/91.
