### ISSUE TITLE
Support relative urls

### ISSUE THREAD

**Issue by Meemaw** [Unleash/unleash-proxy-client-js#94]
### Describe the feature request

Proxy client JS should support relative URLS. 

For example, `/features/proxy` should be a valid URL, and it should rely on the browser behaviour to automatically proxy that through the current origin.

**Comment by Tymek** [comment]
Duplicate of https://github.com/Unleash/unleash-proxy-client-js/issues/59
Thank you for bringing it to our attention. We will prioritize it 👍🏻
